- include: nginx.yml

- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: site daemon is loaded
      template:
        src: daemon.conf
        dest: /etc/init/site.conf
        backup: no

    - name: ensure users are synced
      user:
        name: "{{item.name}}"
        force: yes
        remove: yes
        password: "{{ item.shadow_pass | default(omit) }}"
        state: "{{ item.state | default(omit) }}"
        shell: "{{ item.shell | default('/bin/bash') }}"
        groups: "{{ item.groups | default('sudo') }}"
      with_items: users

    - name: ensure user public keys are synced
      authorized_key:
        user: "{{item.name}}"
        key: "{{ item.public_keys | join('\n') }}"
        state: present
        exclusive: yes
      with_items: users
      when: item.public_keys is defined and item.public_keys | length > 0

    - name: set hostname
      hostname:
        name: "{{hostname}}"

    - name: add loopback references to our domain in /etc/hosts
      lineinfile:
        dest: /etc/hosts
        state: present
        line: "127.0.0.1 {{hostname}} {{site_fqdn}}"
