- hosts: vagrant
  become: yes
  become_method: sudo
  gather_facts: no
  vars:
    user: "{{ lookup('env', 'USER') }}"
    public_key_path: ~/.ssh/id_rsa.pub
  tasks:
    - name: add the current user
      user:
        name: "{{ user }}"
        group: sudo
        shell: /bin/bash

    - name: add the current user's public key
      authorized_key:
        user: "{{ user }}"
        key: "{{ lookup('file', public_key_path) }}"

    - name: allow passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: "^%sudo"
        line: "%sudo\tALL=(ALL:ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"
